app = "openmu-admin"
primary_region = "mia"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ID = "adminPanel"
  ASPNETCORE_URLS = "http://+:8080"
  PATH_BASE = "/admin/"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true
